LANG = {
    "en": {
        "title": "TUS Tracker",
        "subtitle": "Real-time bus monitoring",
        "browse_tab": "Browse",
        "plan_tab": "Plan",
        "search_stop": "Search stop",
        "search_placeholder": "Type stop ID or name to search...",
        "click_info": "Click a stop on the map or use the search bar",
        "scheduled_departures": "Scheduled Departures",
        "no_departures": "No upcoming departures found for this stop.",
        "line": "Line",
        "destination": "Destination",
        "time": "Time",
        "in": "In",
        "min": "min",
        "now": "Now",
        "plan_trip": "Plan Your Trip",
        "query_time": "Query time",
        "query_time_help": "Show schedules for this time of day",
        "coming_soon": "Trip planning features coming soon!",
        "stops":"Stops",
        "selected_stop": "Selected Stop"
    },
    "es": {
        "title": "TUS Tracker",
        "subtitle": "Monitor de autobuses en tiempo real",
        "browse_tab": "Explorar",
        "plan_tab": "Planificar",
        "search_stop": "Buscar parada",
        "search_placeholder": "Escribe el nombre o el número de parada...",
        "click_info": "Pulsa en una parada del mapa o usa el buscador",
        "scheduled_departures": "Próximas Salidas",
        "no_departures": "No se encontraron salidas próximas para esta parada.",
        "line": "Línea",
        "destination": "Destino",
        "time": "Hora",
        "in": "En",
        "min": "min",
        "now": "Ahora",
        "plan_trip": "Planifica tu Viaje",
        "query_time": "Hora de consulta",
        "query_time_help": "Mostrar horarios para esta hora del día",
        "coming_soon": "¡próximamente -> fundionalidades de planificación!",
        "stops":"Paradas",
        "selected_stop": "Parada Seleccionada"
   
    }
}