LANG = {
    "en": {
        "title": "TUS Santander Tracker",
        "subtitle": "Public transport network visualization",
        "browse_tab": "Browse",
        "plan_tab": "Plan",
        "search_stop": "Search stop",
        "search_placeholder": "Type stop ID or name to search...",
        "click_info": "Click a stop on the map or use the search bar",
        "scheduled_departures": "Scheduled Departures",
        "no_departures": "No upcoming departures found for this stop.",
        "line": "Line",
        "destination": "Destination",
        "time": "Time",
        "in": "In",
        "min": "min",
        "now": "Now",
        "plan_trip": "Plan Your Trip",
        "query_time": "Query time",
        "query_time_help": "Show schedules for this time of day",
        "coming_soon": " COMING SOON: \n - 📍 Live bus positions, \n - ⏱️ Real-time arrival predictions (estimaciones), and \n3) 💻 ML-enhanced predictions (currently collecting training data)",
        "stops":"Stops",
        "selected_stop": "Selected Stop"
    },
    "es": {
        "title": "TUS Santander Tracker",
        "subtitle": "Visualización de la red de transporte público",
        "browse_tab": "Explorar",
        "plan_tab": "Planificar",
        "search_stop": "Buscar parada",
        "search_placeholder": "Escribe el nombre o el número de parada...",
        "click_info": "Pulsa en una parada del mapa o usa el buscador",
        "scheduled_departures": "Próximas Salidas",
        "no_departures": "No se encontraron salidas próximas para esta parada.",
        "line": "Línea",
        "destination": "Destino",
        "time": "Hora",
        "in": "En",
        "min": "min",
        "now": "Ahora",
        "plan_trip": "Planifica tu Viaje",
        "query_time": "Hora de consulta",
        "query_time_help": "Mostrar horarios para esta hora del día",
        "coming_soon": " PRÓXIMAMENTE:\n - 📍 Posiciones en vivo de autobuses, \n - ⏱️ Predicciones de llegada en tiempo real (estimaciones), \n - 💻 Predicciones mejoradas con ML (actualmente recopilando datos de entrenamiento)",
        "stops":"Paradas",
        "selected_stop": "Parada Seleccionada"
   
    }
}